# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-21 04:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='comments',
            field=models.TextField(default=datetime.datetime(2019, 5, 21, 4, 31, 25, 916282, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
